routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['web', 'auth'])
    ->namespace('Rapture\Directory\Controllers')
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::resource('directory', 'DirectoryController')->only(['index', 'store', 'destroy']);
        Route::get('directory/reconnect', 'TokenController@store')->name('directory.reconnect');
        Route::get('directory/selection', 'SelectionController@index')->name('directory.selection');
        Route::get('login/bitbucket', 'LoginController@redirectToProvider')->name('directory.login');
        Route::get('login/bitbucket/callback', 'LoginController@handleProviderCallback')->name('directory.callback');
    });

Route::middleware(['web'])
    ->namespace('Rapture\Directory\Controllers')
    ->group(function () {
        Route::get('packages.json', 'PackageFeedController@index');
        Route::get('package/{namespace}/{package}/{version?}', 'DownloadPackageController@verify');
    });

Route::middleware(['api'])
    ->namespace('Rapture\Directory\Controllers')
    ->group(function () {
        Route::post('usage', 'RecordUsageController@store');
        Route::post('repo/pushed', 'WebhookController@store');
        Route::get('/p2/{workspace}/{package}.json', 'PackageFeedController@show');
    });

resources/views/dashboard/index.blade.php
<x-dashboard :title="__('directory::package.plural')">
    <x-heading class="flex justify-between items-center">
        <div>
            <x-h1>@lang('directory::package.plural')</x-h1>

            @if ($auth)
                @if ($auth->isExpired())
                    <small style="display: block; font-size: 14px; line-height: 1.4em; margin-top: 0.25rem">Access Expired</small>
                @else
                    <small style="display: block; font-size: 14px; line-height: 1.4em; margin-top: 0.25rem">Connected: <strong>{{ $auth->username }}</strong></small>
                @endif
            @endif
        </div>

        @if ($auth)
            @can('directory.create', 'directory')
                @if ($auth->isExpired())
                    <x-button href="{{ route('dashboard.directory.reconnect') }}" color="primary">Reconnect</x-button>
                @else
                    <div class="flex items-center justify-end space-x-3">
                        <x-quick-create :action="route('dashboard.directory.store')" placeholder="https://bitbucket.org/raptureapp/core" name="url" icon="plus">
                            <span>@lang('directory::package.submit')</span>
                        </x-quick-create>

                        <x-button href="{{ route('dashboard.directory.selection') }}" icon="folders" color="primary">
                            <span>Browse</span>
                        </x-button>
                    </div>
                @endif
            @endcan
        @endif
    </x-heading>

    @if ($auth)
        <livewire:package-table />
    @else
        <x-container>
            <div class="shadow rounded bg-white p-4 text-center space-y-4">
                <x-button href="{{ route('dashboard.directory.login') }}" class="inline-flex items-center space-x-2" color="primary">
                    <em class="fab fa-bitbucket"></em>
                    <span>Connect Bitbucket</span>
                </x-button>
            </div>
        </x-container>
    @endif
</x-dashboard>

resources/views/repos/selector.blade.php
<div>
    <x-statuses />

    <x-container>
        <div class="space-y-2">
            @if (!empty($viewing))
                <div class="rounded shadow bg-white text-gray-700 cursor-pointer" wire:click="returnToWorkspaces">
                    <div class="px-6 py-4 font-medium flex items-center space-x-4">
                        <em class="far fa-level-up"></em>
                        <span>Return to Workspaces</span>
                    </div>
                </div>
                @foreach ($repos as $repo)
                    <livewire:repo-toggle :exists="in_array($repo['full_name'], $existingRepos)" :repo="$repo" key="repo-{{ $repo['slug'] }}" />
                @endforeach
            @else
                @foreach ($workspaces as $workspace)
                    <div class="rounded shadow bg-white text-gray-700 cursor-pointer px-6 py-4 font-medium uppercase" wire:click="selectWorkspace('{{ $workspace['slug'] }}')" key="workspace-{{ $workspace['slug'] }}">
                        {{ $workspace['name'] }}
                    </div>
                @endforeach
            @endif
        </div>
    </x-container>
</div>

resources/views/repos/toggle.blade.php
<div class="rounded shadow text-gray-700 cursor-pointer px-6 py-4 leading-snug border {{ $errors->has($repo['full_name']) ? 'border-red-400 bg-red-100' : 'border-transparent bg-white' }}">
    <div class="flex items-center justify-between">
        <div>
            <strong>{{ $repo['name'] }}</strong><br>
            <span class="text-gray-500 text-sm">{{ $repo['full_name'] }}</span>
        </div>
        <div class="flex justify-end space-x-4">
            @error($repo['full_name'])
                <div>{{ $message }}</div>
            @enderror

            <div class="w-12 text-center text-lg" wire:loading>
                <em class="far fa-spinner fa-spin"></em>
            </div>
            <span role="checkbox" tabindex="0" class="relative inline-flex flex-shrink-0 h-6 w-12 py-1 px-1 rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring {{ $exists ? 'bg-primary-600' : 'bg-gray-400' }}" wire:click="syncRepo" wire:loading.remove>
                <span aria-hidden="true" class="inline-block h-full w-4 rounded-full bg-white shadow transform transition ease-in-out duration-200 {{ $exists ? 'translate-x-6' : 'translate-x-0' }}"></span>
            </span>
        </div>
    </div>
</div>

resources/views/selection/index.blade.php
<x-dashboard title="Browse Repos">
    <x-heading>
        <div class="flex justify-between items-center">
            <h2 class="text-2xl font-medium leading-7 sm:text-3xl sm:leading-9 sm:truncate">
                Browse Repos
            </h2>
        </div>
    </x-heading>

    <livewire:repo-selector />
</x-dashboard>